apiVersion: v1
kind: List
metadata:
  name: "{{ template "smart-contracts-exporter.name" . }}-extra"
  labels:
    app: "{{ template "smart-contracts-exporter.name" . }}"
items:
{{ toYaml .Values.extra | indent 2 }}
