apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "transfer-sh.name" . }}"
  labels:
    app: "{{ template "transfer-sh.name" . }}"
spec:
  selector:
    matchLabels:
      app: "{{ template "transfer-sh.name" . }}"
  replicas: {{ .Values.replicas }}
  strategy:
{{ toYaml .Values.strategy | trim | indent 4 }}
  template:
    metadata:
      name: "{{ template "transfer-sh.name" . }}"
      labels:
        app: "{{ template "transfer-sh.name" . }}"
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
{{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: "{{ .Values.dnsPolicy }}"
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      containers:
        - name: "{{ template "transfer-sh.name" . }}"
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          args: ["--provider", "{{ .Values.config.provider }}"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
            - containerPort: 6060
              name: profiler
          livenessProbe:
            httpGet:
              path: /
              port: 8080
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: 8080
{{ toYaml .Values.readinessProbe | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ template "transfer-sh.name" $ }}-env"
          env:
{{- if .Values.config.googleAnalyticsKey.secretName }}
            - name: GA_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.config.googleAnalyticsKey.secretName }}"
                  key: "{{ .Values.config.googleAnalyticsKey.key }}"
                  optional: false
{{- end }}
{{- if .Values.config.userVoiceKey.secretName }}
            - name: USERVOICE_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.config.userVoiceKey.secretName }}"
                  key: "{{ .Values.config.userVoiceKey.key }}"
                  optional: false
{{- end }}
{{- if .Values.config.s3.credentials.secretName }}
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.config.s3.credentials.secretName }}"
                  key: "{{ .Values.config.s3.credentials.accessKeyKey }}"
                  optional: false
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.config.s3.credentials.secretName }}"
                  key: "{{ .Values.config.s3.credentials.secretKeyKey }}"
                  optional: false
{{- end }}
{{- if .Values.config.storj.credentials.secretName }}
            - name: STORJ_ACCESS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.config.storj.credentials.secretName }}"
                  key: "{{ .Values.config.storj.credentials.accessKey }}"
                  optional: false
{{- end }}
          volumeMounts:
{{- if .Values.config.gdrive.credentials.secretName }}
            - name: gdrive-creds
              mountPath: /creds/gdrive/
{{- end }}
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
      volumes:
{{- if .Values.config.gdrive.credentials.secretName }}
        - name: gdrive-creds
          secret:
            secretName: "{{ .Values.config.gdrive.credentials.secretName }}"
            items:
              - key: "{{ .Values.config.gdrive.credentials.clientJsonKey }}"
                path: client.json
{{- end }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
