{{- if .Values.service.enabled }}
{{- $serviceValues := .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "transfer-sh.name" $ }}"
  labels:
    app: "{{ template "transfer-sh.name" $ }}"
spec:
  type: {{ $serviceValues.type }}
  {{- if $serviceValues.clusterIP }}
  clusterIP: {{ $serviceValues.clusterIP }}
  {{- end }}
  {{- if $serviceValues.externalIPs }}
  externalIPs:
  {{ toYaml $serviceValues.externalIPs | indent 4 }}
  {{- end }}
  {{- if $serviceValues.loadBalancerIP }}
  loadBalancerIP: {{ $serviceValues.loadBalancerIP }}
  {{- end }}
  {{- if $serviceValues.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := $serviceValues.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- if ne $serviceValues.type "ClusterIP" }}
  externalTrafficPolicy: {{ $serviceValues.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
    - port: 6060
      targetPort: profiler
      protocol: TCP
      name: profiler
  selector:
    app: "{{ template "transfer-sh.name" $ }}"
{{- end }}
