apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "supervisor.name" $ }}-env"
  labels:
    app: "{{ template "supervisor.name" $ }}"
data:
  TLS_ENABLE: "{{ .Values.config.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.tls.enable }}
  TLS_KEY: "{{ .Values.config.tls.key }}"
  TLS_CERT: "{{ .Values.config.tls.cert }}"
{{- end }}

  METASCHEDULER_ENDPOINT: "{{ .Values.config.metascheduler.endpoint }}"
  METASCHEDULER_SMART_CONTRACT: "{{ .Values.config.metascheduler.smartContract }}"

  ORACLE_ENDPOINT: "{{ .Values.config.oracle.endpoint }}"
  ORACLE_TLS_ENABLE: "{{ .Values.config.oracle.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.oracle.tls.enable }}
  ORACLE_CA: "{{ .Values.config.oracle.tls.ca }}"
  ORACLE_SERVER_HOST_OVERRIDE: "{{ .Values.config.oracle.tls.serverHostOverride }}"
{{- end }}

  SLURM_SSH_ADDRESS: "{{ .Values.config.slurm.ssh.address }}"
  SLURM_SSH_ADMIN_USER: "{{ .Values.config.slurm.ssh.adminUser }}"

  SLURM_SBATCH_PATH: "{{ .Values.config.slurm.paths.sbatch }}"
  SLURM_SCANCEL_PATH: "{{ .Values.config.slurm.paths.scancel }}"
  SLURM_SQUEUE_PATH: "{{ .Values.config.slurm.paths.squeue }}"
  SLURM_SCONTROL_PATH: "{{ .Values.config.slurm.paths.scontrol }}"

  TOTAL_NODES: "{{ .Values.config.spec.nodes }}"
  TOTAL_CPUS: "{{ .Values.config.spec.cpus }}"
  TOTAL_GPUS: "{{ .Values.config.spec.gpus }}"
  TOTAL_MEMORY: "{{ .Values.config.spec.memory }}"
