apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "supervisor.name" $ }}-env"
  labels:
    app: "{{ template "supervisor.name" $ }}"
data:
  PUBLIC_ADDRESS: "{{ .Values.config.publicAddress }}"
  TLS_ENABLE: "{{ .Values.config.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.tls.enable }}
  TLS_KEY: "{{ .Values.config.tls.key }}"
  TLS_CERT: "{{ .Values.config.tls.cert }}"
{{- end }}

  METASCHEDULER_ENDPOINT_RPC: "{{ .Values.config.metascheduler.endpoint.rpc }}"
  METASCHEDULER_ENDPOINT_WS: "{{ .Values.config.metascheduler.endpoint.ws }}"
  METASCHEDULER_SMART_CONTRACT: "{{ .Values.config.metascheduler.smartContract }}"

  SBATCH_ENDPOINT: "{{ .Values.config.sbatchService.endpoint }}"
  SBATCH_TLS_ENABLE: "{{ .Values.config.sbatchService.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.sbatchService.tls.enable }}
  SBATCH_TLS_INSECURE: "{{ .Values.config.sbatchService.tls.insecure | ternary "true" "false" }}"
  SBATCH_CA: "{{ .Values.config.sbatchService.tls.ca }}"
{{- end }}

  SLURM_SSH_ADDRESS: "{{ .Values.config.slurm.ssh.address }}"
  SLURM_SSH_ADMIN_USER: "{{ .Values.config.slurm.ssh.adminUser }}"

  SLURM_SBATCH_PATH: "{{ .Values.config.slurm.paths.sbatch }}"
  SLURM_SCANCEL_PATH: "{{ .Values.config.slurm.paths.scancel }}"
  SLURM_SQUEUE_PATH: "{{ .Values.config.slurm.paths.squeue }}"
  SLURM_SCONTROL_PATH: "{{ .Values.config.slurm.paths.scontrol }}"
  SLURM_PARTITION: "{{ .Values.config.slurm.partition }}"

  TOTAL_NODES: "{{ .Values.config.spec.nodes }}"
  TOTAL_CPUS: "{{ .Values.config.spec.cpus }}"
  TOTAL_GPUS: "{{ .Values.config.spec.gpus }}"
  TOTAL_MEMORY: "{{ .Values.config.spec.memory }}"

  BENCHMARK_IMAGE: "{{ .Values.config.benchmark.image }}"
  BENCHMARK_SINGLE_NODE: "{{ .Values.config.benchmark.singleNode | ternary "true" "false" }}"
  BENCHMARK_DISABLE: "{{ .Values.config.benchmark.disable | ternary "true" "false" }}"
