apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "supervisor.name" $ }}-env"
  labels:
    app: "{{ template "supervisor.name" $ }}"
data:
  TLS_ENABLE: "{{ .Values.config.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.tls.enable }}
  TLS_KEY: "{{ .Values.config.tls.key }}"
  TLS_CERT: "{{ .Values.config.tls.cert }}"
{{- end }}

  METASCHEDULER_ENDPOINT_RPC: "{{ .Values.config.metascheduler.endpoint.rpc }}"
  METASCHEDULER_ENDPOINT_WS: "{{ .Values.config.metascheduler.endpoint.ws }}"
  METASCHEDULER_SMART_CONTRACT: "{{ .Values.config.metascheduler.smartContract }}"

  CUSTOMER_ENDPOINT: "{{ .Values.config.customer.endpoint }}"
  CUSTOMER_TLS_ENABLE: "{{ .Values.config.customer.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.customer.tls.enable }}
  CUSTOMER_TLS_INSECURE: "{{ .Values.config.customer.tls.insecure | ternary "true" "false" }}"
  CUSTOMER_CA: "{{ .Values.config.customer.tls.ca }}"
  CUSTOMER_SERVER_HOST_OVERRIDE: "{{ .Values.config.customer.tls.serverHostOverride }}"
{{- end }}

  SLURM_SSH_ADDRESS: "{{ .Values.config.slurm.ssh.address }}"
  SLURM_SSH_ADMIN_USER: "{{ .Values.config.slurm.ssh.adminUser }}"

  SLURM_SBATCH_PATH: "{{ .Values.config.slurm.paths.sbatch }}"
  SLURM_SCANCEL_PATH: "{{ .Values.config.slurm.paths.scancel }}"
  SLURM_SQUEUE_PATH: "{{ .Values.config.slurm.paths.squeue }}"
  SLURM_SCONTROL_PATH: "{{ .Values.config.slurm.paths.scontrol }}"

  TOTAL_NODES: "{{ .Values.config.spec.nodes }}"
  TOTAL_CPUS: "{{ .Values.config.spec.cpus }}"
  TOTAL_GPUS: "{{ .Values.config.spec.gpus }}"
  TOTAL_MEMORY: "{{ .Values.config.spec.memory }}"
