apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "sbatch-service.name" $ }}-env"
  labels:
    app: "{{ template "sbatch-service.name" $ }}"
data:
{{- if ne .Values.config.redis.address "" }}
  REDIS_ADDRESS: "{{ .Values.config.redis.address }}"
  REDIS_TLS_ENABLE: "{{ .Values.config.redis.tls.enable | ternary "true" "false" }}"
{{- if .Values.config.redis.tls.enable }}
  REDIS_TLS_INSECURE: "{{ .Values.config.redis.tls.insecure | ternary "true" "false" }}"
  REDIS_CA: "{{ .Values.config.redis.tls.ca }}"
  REDIS_SERVER_HOST_OVERRIDE: "{{ .Values.config.redis.tls.serverHostOverride }}"
{{- end }}
{{- else }}
  REDIS_ADDRESS: "{{ printf "redis://%s-master:%d/0" (include "sbatch-service.redis.fullname" $) (.Values.redis.master.service.ports.redis | int) }}"
  REDIS_TLS_ENABLE: "false"
{{- end }}

  LOGGER_WRITER_PATH: "{{ .Values.config.logger.writer.path }}"
  LOGGER_ENDPOINT: "{{ .Values.config.logger.endpoint }}"

  HOOK_PRE_PATH: "{{ .Values.config.hook.pre.path }}"
  HOOK_POST_PATH: "{{ .Values.config.hook.post.path }}"

  DEBUG: "{{ .Values.config.debug  | ternary "true" "false" }}"
